change from model to scene with node hierarchies
ProtoArt/spritec pull request #74
Opened 2019-08-26 13:30 UTC by daose

Part of #71, implements the `gatherNodes` functionality. Tested by running `cargo run samples/bigboi/spritec.toml` and making sure the outputs look the same as before.

Changes `Model` -> `Scene`. A Scene is a tree hierarchy of nodes where each node has its own local transform.

glTF files are converted to `Scene` since it's already scene-based, and .obj files are converted as 1 node containing all the meshes.

2019-08-27 01:47 UTC, sunjay commented
@JLSJamesShi you do the first review and I'll review after that. There are many aspects to reviewing including:

1. Does the code do what it is meant to do? If you don't know what this is, your job is to find out with Bill's help.
2. Make sure you understand what the code is doing, why it works, and why this is the best way to do it. This involves thinking about if there are other ways to write the code and then thinking about the various trade-offs. There are a lot of different versions that could be the "best".
3. Look at code style, maintainability, documentation (comments), etc.

There are articles online about what to look for if you want to know more. You can also look at my old reviews in our other PRs and see if you can pick anything up there. The most important thing is that you should make sure we're solving the right problem and try to get close to code you would want to work with in our codebase. You will also be balancing the fact that we want to get things merged as soon as possible. 

I'll chime in and mentor if you need anything. Feel free to ping me with questions. :)

2019-11-10 19:11 UTC, JLSJamesShi commented on src/lib.rs
> -            model_inverse_transpose: model.inverted().transposed(),
Are we still keeping some sort of model, since we're inverting and transposing one here?

2019-11-18 03:51 UTC, JLSJamesShi requested changes
Good job BOLL!!!!!!

Only other thing to note is that we might want to move the scene.rs and node.rs files into its own directory under src/

2019-11-18 03:51 UTC, JLSJamesShi commented on src/lib.rs
> +                let mvp = view_projection_matrix * model;
Can we rename model to something like model_trans to differentiate between a model of some sort and the model transformation matrix?

2019-11-18 03:51 UTC, JLSJamesShi commented on src/lib.rs
> +                    mvp, mesh: &mesh, outline_color, outline_thickness
Can you put each of these on its own line?

2019-11-18 03:51 UTC, JLSJamesShi commented on src/lib.rs
> +                    mvp, mesh: &mesh, outline_color, outline_thickness
The type of mesh at this point is &Mesh already due to Rust automatically taking a reference when pattern matching. The "&" added here is redundant, so we don't need it. Same change needed for CelShader below.

2019-11-18 03:51 UTC, JLSJamesShi commented on src/lib.rs
> +                    mesh.indices(), color, depth
Similarly separate this into multiple lines.

2019-11-18 03:51 UTC, JLSJamesShi commented on src/loaders/gltf.rs
> +        Scene::from_gltf(&self.document, &self.buffers, &self.materials)
Have this calculation be done in load_file and just return that instead of recalculating.

2019-11-18 03:51 UTC, JLSJamesShi commented on src/tasks/spritesheet.rs
>      /// An array of models to render for each frame
Comment should say "an array of scenes..."

2019-11-18 03:51 UTC, JLSJamesShi commented on src/loaders/gltf.rs
> -        // that primitive refers to is loaded in the same order as document.materials()
Keep the comment in so that our assumption is explicit.

2019-11-18 03:51 UTC, JLSJamesShi commented on src/loaders/gltf.rs
> +        */
Hi Sunjay, how's life?
Bill says he needs this for the next PR and it will be removed in the next PR.
GOODBYE FOREVER.

2019-11-18 03:51 UTC, JLSJamesShi commented on src/tasks/pose.rs
> +    model: Scene,
Rename model to scene to be thorough.

2019-11-18 03:51 UTC, JLSJamesShi commented on src/tasks/spritesheet.rs
> +    Models(Vec<Scene>),
Rename Models to Scenes.

2019-11-21 03:19 UTC, daose commented on src/loaders/gltf.rs
> -        // that primitive refers to is loaded in the same order as document.materials()
moved it to `src/model/geometry.rs` where the assumption is actually used

2020-01-07 00:49 UTC, sunjay approved these changes
Thanks @daose! This looks great. I'm going to merge it as soon as CI passes. The only changes I made were to 1) update to the latest master, and 2) delete a call to `clone` that was redundant (clippy fix).

@JLSJamesShi's excellent review caught any outstanding issues I would have wanted to address, so this is ready to go! Thanks James for your great work! :grin: 

Next step: I'm going to merge this into master and then merge that into my layout-engine branch. Once that's fully integrated, the layout engine will be ready for a PR! :tada:

2020-01-07 00:49 UTC, sunjay approved these changes
Thanks @daose! This looks great. I'm going to merge it as soon as CI passes. The only changes I made were to 1) update to the latest master, and 2) delete a call to `clone` that was redundant (clippy fix).

@JLSJamesShi's excellent review caught any outstanding issues I would have wanted to address, so this is ready to go! Thanks James for your great work! :grin: 

Next step: I'm going to merge this into master and then merge that into my layout-engine branch. Once that's fully integrated, the layout engine will be ready for a PR! :tada:

2020-01-07 01:18 UTC, JLSJamesShi approved these changes

2020-01-07 01:19 UTC, merged

2020-01-07 01:20 UTC, sunjay commented
Appreciate all your work on this @daose! Thanks for the great reviewing @JLSJamesShi!